#!/usr/bin/env python3
"""Generate CN v0.3 evidence maps for remaining Core comparators."""
import json
from pathlib import Path

ROOT = Path("/workspace/v1.39-BaselineRohitHandover")
CN = json.loads((ROOT / "canonical-model/CN_v0.3_Canonical_Capability_Model.json").read_text())
OUT = ROOT / "kbs"

PARTIAL = "Partial Parity"
FULL = "Full Parity"
NO = "No Parity"


def feat(parity, component, key, notes, workaround=None, complexity=None, impact=None):
    d = {
        "parity": parity,
        "primaryComponent": component,
        "evidenceKey": key,
        "notes": notes,
    }
    if parity == PARTIAL:
        d["workaround"] = workaround or "Use platform-native equivalent with redesign."
        d["workaroundComplexity"] = complexity or "Medium"
        d["technicalImpact"] = impact or "Not a 1:1 VCF equivalent; operating model differs."
    return d


def all_features(assign_fn):
    out = {}
    for p in CN["products"]:
        for f in p["features"]:
            out[f["featureId"]] = assign_fn(p["productId"], f["featureId"], f["name"])
    assert len(out) == 84, len(out)
    return out


def azure(pid, fid, name):
    # HCI cluster ops strong; NSX/SDDC Manager/VCF AI weak
    table = {
        "VCF-01-F01": feat(FULL, "Azure Local / Azure Arc", "azureLocal", "Azure Local clusters register to Azure Arc for inventory and topology visibility."),
        "VCF-01-F02": feat(PARTIAL, "Azure Local", "azureLocal", "No VCF Workload Domain construct; scale by adding cluster nodes/clusters.",
                           "Create/expand Azure Local clusters instead of VCF workload domains.", "Medium",
                           "Domain lifecycle UX and isolation model differ from SDDC Manager."),
        "VCF-01-F03": feat(FULL, "Failover Clustering / Azure Local", "azureLocal", "Add/remove nodes via Azure Local cluster operations."),
        "VCF-01-F04": feat(PARTIAL, "Azure Local / Arc RBAC", "arc", "Management vs workload isolation uses Azure RBAC/resource groups, not VCF domains.",
                           "Separate Arc resource groups and RBAC scopes for management vs workloads.", "Medium",
                           "Principal/workload domain semantics are not 1:1."),
        "VCF-01-F05": feat(FULL, "Azure Local deployment", "deploy", "Host imaging and cluster bring-up are documented Azure Local deployment workflows."),
        "VCF-01-F06": feat(PARTIAL, "Azure Policy / Arc", "arc", "Desired-state via Azure Policy/Arc, not VCF configuration baselines.",
                           "Apply Azure Policy and Arc configuration to cluster resources.", "Medium",
                           "Baseline/drift model differs from SDDC Manager."),
        "VCF-01-F07": feat(PARTIAL, "Storage Replica / stretched clustering", "s2d", "Stretched/multi-site patterns exist but are not VCF stretch-domain native.",
                           "Design stretched Azure Local / Storage Replica topologies.", "High",
                           "Site affinity and failure-domain UX differ."),
        "VCF-02-F01": feat(PARTIAL, "Azure Local installer", "deploy", "Cluster deployment wizard exists; not VCF Installer.",
                           "Use Azure Local deployment tools instead of VCF bring-up.", "Medium", "Prerequisite model differs."),
        "VCF-02-F02": feat(NO, "N/A", "azureLocal", "No SDDC Manager equivalent orchestrating VCF-style domain workflows."),
        "VCF-02-F03": feat(PARTIAL, "Windows Admin Center / Update", "update", "Update catalogs differ from VCF depot/bundles.",
                           "Use Azure Local solution updates / WAC update flows.", "Medium", "Bundle schema is not VCF depot."),
        "VCF-02-F04": feat(PARTIAL, "Solution updates", "update", "Prechecks exist in solution update workflows.",
                           "Run Azure Local update readiness checks.", "Medium", "Blocker reporting differs from VCF precheck packs."),
        "VCF-02-F05": feat(PARTIAL, "Solution updates", "update", "Coordinated OS/HCI updates, not full VCF stack upgrade.",
                           "Use Azure Local solution update to roll hosts.", "Medium", "Does not upgrade NSX/vCenter-class stack."),
        "VCF-02-F06": feat(PARTIAL, "Update rings", "update", "Selective deferral via update rings/policies.",
                           "Stage updates with maintenance windows.", "Medium", "Skip-level controls are not VCF-identical."),
        "VCF-02-F07": feat(PARTIAL, "Azure Activity Log", "arc", "History via Azure/WAC; rollback often reimage-constrained.",
                           "Retain update history; plan rollback as restore/reimage.", "High", "Rollback posture weaker than full VCF stack rollback."),
        "VCF-03-F01": feat(FULL, "Hyper-V", "hyperv", "Hyper-V on Azure Local provides VM compute services."),
        "VCF-03-F02": feat(FULL, "Windows Admin Center / Arc", "wac", "Central inventory, RBAC, and APIs via WAC and Azure Arc."),
        "VCF-03-F03": feat(FULL, "Failover Clustering", "hyperv", "Live migration and cluster-aware placement for VMs."),
        "VCF-03-F04": feat(FULL, "Failover Clustering", "hyperv", "Cluster HA restarts VMs on host failure."),
        "VCF-03-F05": feat(PARTIAL, "Hyper-V", "hyperv", "Hyper-V resource controls exist; not vSphere resource pools.",
                           "Use VM limits/weights and host groups.", "Low", "Pool semantics differ from vSphere."),
        "VCF-03-F06": feat(FULL, "Hyper-V", "hyperv", "Provision, clone, checkpoint/restore are core Hyper-V operations."),
        "VCF-03-F07": feat(FULL, "Failover Clustering", "hyperv", "Drain/maintenance and live migration supported."),
        "VCF-04-F01": feat(FULL, "Storage Spaces Direct", "s2d", "S2D provides software-defined shared volumes for VMs."),
        "VCF-04-F02": feat(PARTIAL, "Storage Spaces Direct", "s2d", "Volume resiliency settings exist; not vSAN SPBM.",
                           "Use S2D resiliency/tiering policies per volume.", "Medium", "Policy-to-VM binding is less granular than SPBM."),
        "VCF-04-F03": feat(FULL, "ReFS / S2D", "s2d", "Dedup/compression/efficiency features available on S2D/ReFS."),
        "VCF-04-F04": feat(FULL, "Storage Spaces Direct", "s2d", "Fault domains and rebuild are core S2D capabilities."),
        "VCF-04-F05": feat(PARTIAL, "Storage Replica", "s2d", "Stretched storage via Storage Replica / stretched cluster designs.",
                           "Design Storage Replica or stretched S2D.", "High", "Not identical to vSAN stretch."),
        "VCF-04-F06": feat(PARTIAL, "File Services / Azure Files", "s2d", "File shares via Windows File Services or Azure Files.",
                           "Add file services role or hybrid Azure Files.", "Medium", "Packaging differs from vSAN File Services."),
        "VCF-04-F07": feat(FULL, "Windows Admin Center", "wac", "Health, support logs, and rebuild visibility in WAC/S2D."),
        "VCF-05-F01": feat(PARTIAL, "Network ATC / SDN", "sdn", "Logical networks exist; not NSX segments.",
                           "Use Network ATC, SET, and optional SDN virtual networks.", "Medium", "Segment model differs from NSX."),
        "VCF-05-F02": feat(PARTIAL, "SDN gateways", "sdn", "SDN gateways provide routing; not NSX Tier-0/1.",
                           "Map T0/T1 designs to SDN gateway/VLAN patterns.", "High", "Routing taxonomy is not NSX."),
        "VCF-05-F03": feat(PARTIAL, "SDN Software Load Balancer", "sdn", "SLB/NAT available; not NSX Edge feature set.",
                           "Use SDN SLB and Windows gateway VMs.", "High", "Edge services depth is lower than NSX."),
        "VCF-05-F04": feat(PARTIAL, "Azure VNets / SDN", "sdn", "Multi-tenant isolation via VNets/SDN; not NSX VPC.",
                           "Use SDN network controller isolation or Azure VNet constructs.", "Medium", "Tenant networking UX differs."),
        "VCF-05-F05": feat(PARTIAL, "Network ATC", "sdn", "Intent-based host networking; overlay/underlay ops differ.",
                           "Validate RDMA/SET underlay per Azure Local networking guidance.", "Medium", "No NSX transport-zone model."),
        "VCF-05-F06": feat(PARTIAL, "Windows DHCP / Azure DNS", "sdn", "DHCP/DNS typically hybrid Windows/Azure.",
                           "Use Windows DHCP and Azure DNS/private DNS.", "Low", "IPAM depth below NSX."),
        "VCF-05-F07": feat(PARTIAL, "WAC / Azure Monitor", "monitor", "Basic network health via WAC/Azure Monitor.",
                           "Use Azure Monitor and packet capture tooling.", "Medium", "No NSX Traceflow equivalent."),
        "VCF-06-F01": feat(PARTIAL, "Windows Firewall / NSG", "security", "Host/NSG controls; not NSX DFW.",
                           "Combine Windows Firewall, NSGs, and microseg products.", "High", "East-west DFW parity is incomplete."),
        "VCF-06-F02": feat(PARTIAL, "Azure Firewall / NSG", "security", "North-south via NSG/Azure Firewall patterns.",
                           "Place Azure Firewall or gateway ACLs at perimeter.", "Medium", "Not NSX gateway firewall."),
        "VCF-06-F03": feat(PARTIAL, "Azure tags / NSG", "arc", "Dynamic grouping via tags/Arc; not NSX security groups.",
                           "Use Azure tags, Arc, and policy-based grouping.", "Medium", "Auto-membership semantics differ."),
        "VCF-06-F04": feat(PARTIAL, "Microsoft Defender", "security", "IDS/IPS-class via Defender/partner.",
                           "Enable Defender for Cloud / partner NVA insertion.", "High", "License and partner dependent."),
        "VCF-06-F05": feat(PARTIAL, "Entra ID", "security", "Identity-aware controls via Entra ID conditional access.",
                           "Bind RBAC and Conditional Access; not NSX identity firewall.", "High", "Context-aware DFW incomplete."),
        "VCF-06-F06": feat(PARTIAL, "Azure Policy", "arc", "Change control via Policy/GitOps.",
                           "Stage policy in Azure Policy/Git.", "Medium", "Publish/rollback differs from NSX."),
        "VCF-06-F07": feat(PARTIAL, "Defender / Azure Policy", "security", "Compliance dashboards exist.",
                           "Export Defender/Policy compliance reports.", "Medium", "Evidence packs differ from NSX."),
        "VCF-07-F01": feat(FULL, "Azure Monitor / Insights", "monitor", "Infrastructure metrics and dashboards via Azure Monitor."),
        "VCF-07-F02": feat(PARTIAL, "Azure Monitor Logs", "monitor", "Log Analytics; not Aria Logs.",
                           "Ingest to Log Analytics / Sentinel.", "Medium", "May need Sentinel for SIEM-class analysis."),
        "VCF-07-F03": feat(PARTIAL, "Azure Monitor", "monitor", "Capacity insights via Monitor/WAC.",
                           "Use VM insights and S2D capacity views.", "Medium", "Forecasting depth differs from Aria."),
        "VCF-07-F04": feat(PARTIAL, "Azure Policy", "arc", "Config/compliance via Policy.",
                           "Assign Azure Policy initiatives to Arc resources.", "Medium", "Content packs differ from Aria."),
        "VCF-07-F05": feat(PARTIAL, "VM Insights", "monitor", "Limited app mapping vs Aria.",
                           "Use VM Insights map and tags.", "Medium", "Dependency mapping shallower."),
        "VCF-07-F06": feat(FULL, "Azure Monitor alerts", "monitor", "Alert rules and action groups supported."),
        "VCF-07-F07": feat(FULL, "Azure Monitor", "monitor", "Workbooks and export for operational evidence."),
        "VCF-08-F01": feat(PARTIAL, "Azure Automation / Arc", "arc", "Self-service via Azure portal/Automation, not Aria catalog.",
                           "Publish runbooks/templates in Automation or Service Management Automation.", "Medium", "Catalog UX differs."),
        "VCF-08-F02": feat(FULL, "Bicep / ARM / Terraform", "arc", "IaC templates are first-class for Azure Local/Arc."),
        "VCF-08-F03": feat(PARTIAL, "Azure Policy / ITSM", "arc", "Approvals via ITSM/Azure Lighthouse patterns.",
                           "Integrate ServiceNow/approvals with pipelines.", "Medium", "Less turnkey than Aria ABX approvals."),
        "VCF-08-F04": feat(PARTIAL, "Azure Automation", "arc", "Day-2 via runbooks/Azure Update Manager.",
                           "Encode day-2 as Automation/runbooks.", "Medium", "Blueprint day-2 model differs."),
        "VCF-08-F05": feat(PARTIAL, "Azure RBAC", "arc", "Subscriptions/RGs as tenancy.",
                           "Use management groups and RBAC.", "Medium", "Project/tenant catalog isolation differs."),
        "VCF-08-F06": feat(PARTIAL, "Azure Logic Apps / APIs", "arc", "ITSM via Logic Apps/webhooks.",
                           "Connect pipelines and ServiceNow via APIs.", "Medium", "Connector pack differs from Aria."),
        "VCF-08-F07": feat(FULL, "Azure APIs", "arc", "Extensibility via REST, Event Grid, credentials in Key Vault."),
        "VCF-09-F01": feat(PARTIAL, "AKS on Azure Local", "aks", "AKS hybrid cluster lifecycle, not vSphere Supervisor.",
                           "Use AKS on Azure Local for Kubernetes lifecycle.", "Medium", "Not VKS Supervisor model."),
        "VCF-09-F02": feat(FULL, "Kubernetes", "aks", "Namespaces, quotas, RBAC are standard Kubernetes."),
        "VCF-09-F03": feat(PARTIAL, "AKS CNI", "aks", "Pod/service networking via AKS CNI, not NSX-VKS.",
                           "Use AKS networking plus Azure CNI/Calico.", "Medium", "SDN integration differs."),
        "VCF-09-F04": feat(FULL, "Container Storage", "aks", "CSI/persistent volumes on Azure Local storage."),
        "VCF-09-F05": feat(PARTIAL, "ACR", "aks", "Azure Container Registry integration.",
                           "Attach ACR or Harbor.", "Low", "Registry packaging differs from VCF."),
        "VCF-09-F06": feat(PARTIAL, "AKS policy", "aks", "Pod security/admission via AKS policy.",
                           "Enable Azure Policy for AKS and secrets CSI.", "Medium", "Security pack differs from VKS."),
        "VCF-09-F07": feat(PARTIAL, "AKS", "aks", "Dev self-service via kubectl/portal/GitOps.",
                           "Expose AKS APIs and GitOps.", "Medium", "Developer UX differs from Tanzu/VKS."),
        "VCF-10-F01": feat(PARTIAL, "Azure Migrate / SCVMM", "migrate", "Cold migration via Azure Migrate / Hyper-V import.",
                           "Use Azure Migrate or offline disk conversion.", "Medium", "Not HCX bulk migrate."),
        "VCF-10-F02": feat(PARTIAL, "Hyper-V live migration", "hyperv", "Live migration within cluster; limited cross-fabric vs HCX.",
                           "Use intra-cluster live migration; plan cutover for cross-platform.", "High", "No HCX vMotion fabric."),
        "VCF-10-F03": feat(PARTIAL, "Azure Migrate", "migrate", "Replication-assisted migrate to Azure Local paths exist.",
                           "Use Azure Migrate replication then cutover.", "Medium", "Tooling differs from HCX RAV."),
        "VCF-10-F04": feat(NO, "N/A", "migrate", "No HCX-class L2 network extension product equivalent."),
        "VCF-10-F05": feat(PARTIAL, "Azure Local", "azureLocal", "Converge existing Hyper-V estates operationally.",
                           "Onboard existing clusters to Azure Local/Arc.", "High", "No VCF Import/Converge product."),
        "VCF-10-F06": feat(PARTIAL, "Azure Migrate", "migrate", "Wave tracking in Azure Migrate projects.",
                           "Plan waves in Azure Migrate.", "Medium", "Less HCX-centric wave ops."),
        "VCF-10-F07": feat(PARTIAL, "Azure Migrate", "migrate", "Rollback is keep-source-until-cutover.",
                           "Define cutover windows and retain source.", "Medium", "Rollback is process-driven."),
        "VCF-11-F01": feat(FULL, "Azure Backup / MABS", "backup", "VM backup via Azure Backup / MABS on Azure Local."),
        "VCF-11-F02": feat(FULL, "Azure Backup", "backup", "Restore workloads from Recovery Services."),
        "VCF-11-F03": feat(PARTIAL, "Hyper-V Replica / ASR", "backup", "DR orchestration via Replica/ASR patterns.",
                           "Use Hyper-V Replica or Azure Site Recovery where supported.", "Medium", "Not VMware SRM/HCX DR identical."),
        "VCF-11-F04": feat(PARTIAL, "Azure Backup", "backup", "Backup policies encode RPO; RTO depends on design.",
                           "Define vault policies and test restores.", "Medium", "SLA dashboards differ."),
        "VCF-11-F05": feat(PARTIAL, "Immutable vaults", "backup", "Immutability options in Recovery Services.",
                           "Enable immutable vault / soft-delete.", "Medium", "Cyber-recovery design still required."),
        "VCF-11-F06": feat(PARTIAL, "VSS / app agents", "backup", "App-consistent via VSS/SQL agents.",
                           "Use application-consistent backup agents.", "Medium", "Agent coverage is workload-specific."),
        "VCF-11-F07": feat(PARTIAL, "Backup reports", "backup", "Backup reporting in Azure portal.",
                           "Export backup/DR test evidence from Azure.", "Low", "Report format differs."),
        "VCF-12-F01": feat(PARTIAL, "GPU-P / DDA", "hyperv", "GPU partition/DDA on Hyper-V.",
                           "Enable GPU-P or DDA for VMs.", "Medium", "Not VCF Private AI packaging."),
        "VCF-12-F02": feat(NO, "N/A", "azureLocal", "No first-class VCF Private AI model-serving product on Azure Local."),
        "VCF-12-F03": feat(NO, "N/A", "azureLocal", "RAG pipelines are solution-assembled, not a platform product."),
        "VCF-12-F04": feat(NO, "N/A", "azureLocal", "No built-in MLOps equivalent to VCF Private AI Services."),
        "VCF-12-F05": feat(PARTIAL, "Entra ID / RBAC", "arc", "General platform RBAC only.",
                           "Govern GPU/AI VMs with RBAC and Policy.", "Medium", "AI-specific governance is limited."),
        "VCF-12-F06": feat(PARTIAL, "Azure Local", "azureLocal", "AI VMs can use platform identity/network/storage.",
                           "Run AI workloads as VMs/AKS on the HCI stack.", "Medium", "DIY vs packaged VCF Private AI."),
        "VCF-12-F07": feat(PARTIAL, "On-prem Azure Local", "azureLocal", "On-prem inference possible; egress must be designed.",
                           "Keep models on-prem; control outbound with firewall.", "Medium", "Sovereign controls are design-dependent."),
    }
    return table[fid]


def openshift(pid, fid, name):
    table = {
        "VCF-01-F01": feat(PARTIAL, "OpenShift web console", "ocp", "Cluster/node inventory exists; not VCF fleet/workload domains.",
                           "Use OpenShift console and ACM for multi-cluster inventory.", "Medium", "No VCF domain topology."),
        "VCF-01-F02": feat(NO, "N/A", "ocp", "No VCF Workload Domain lifecycle."),
        "VCF-01-F03": feat(PARTIAL, "MachineSets", "ocp", "Node add/remove via Machine API, not VCF cluster composition.",
                           "Scale MachineSets / host scaling.", "Medium", "Host model is Kubernetes Machines, not ESXi clusters."),
        "VCF-01-F04": feat(PARTIAL, "ACM / Hive", "acm", "Hub vs spoke isolation via ACM, not VCF management domain.",
                           "Use ACM hub cluster plus managed clusters.", "Medium", "Isolation model differs."),
        "VCF-01-F05": feat(PARTIAL, "Assisted Installer / IPI", "install", "Node bring-up via Assisted Installer/IPI.",
                           "Commission hosts with Assisted Installer.", "Medium", "Not VCF host commissioning."),
        "VCF-01-F06": feat(PARTIAL, "GitOps / Policy", "gitops", "Desired state via GitOps, not VCF baselines.",
                           "Enforce cluster desired state with ACM policies/GitOps.", "Medium", "Drift tooling differs."),
        "VCF-01-F07": feat(PARTIAL, "ACM", "acm", "Multi-site as multiple clusters.",
                           "Model sites as ACM-managed clusters.", "High", "No VCF stretch-domain object."),
        "VCF-02-F01": feat(PARTIAL, "Assisted Installer", "install", "OpenShift install, not VCF Installer.",
                           "Use Assisted Installer / Agent-based installer.", "Medium", "Bring-up UX differs."),
        "VCF-02-F02": feat(NO, "N/A", "ocp", "No SDDC Manager orchestration of VCF components."),
        "VCF-02-F03": feat(PARTIAL, "OSUS / oc-mirror", "upgrade", "Release images via OSUS/oc-mirror, not VCF depot.",
                           "Mirror release payloads for disconnected upgrades.", "Medium", "Bundle format differs."),
        "VCF-02-F04": feat(FULL, "Cluster Version Operator", "upgrade", "Upgrade prechecks via CVO/health operators."),
        "VCF-02-F05": feat(PARTIAL, "CVO", "upgrade", "Coordinates OCP upgrades, not VCF full stack (NSX/vSAN/vCenter).",
                           "Upgrade OpenShift + OLM operators as a set.", "Medium", "Does not upgrade a VCF-equivalent stack."),
        "VCF-02-F06": feat(PARTIAL, "Channel / paused operators", "upgrade", "Channels and paused operator updates.",
                           "Select upgrade channel; pause non-critical operators.", "Medium", "Not VCF skip-level controls."),
        "VCF-02-F07": feat(PARTIAL, "CVO history", "upgrade", "Upgrade history in cluster version; rollback constrained.",
                           "Retain CVO history; rollback via restore/reinstall patterns.", "High", "Full stack rollback is limited."),
        "VCF-03-F01": feat(FULL, "OpenShift Virtualization / KubeVirt", "virt", "KubeVirt runs VMs as first-class workloads on OpenShift."),
        "VCF-03-F02": feat(FULL, "OpenShift API / console", "ocp", "Central inventory, RBAC, and APIs for VMs and cluster."),
        "VCF-03-F03": feat(PARTIAL, "KubeVirt live migration", "virt", "Live migration exists; not DRS.",
                           "Use live migration and node placement/taints.", "Medium", "No vSphere DRS equivalent."),
        "VCF-03-F04": feat(PARTIAL, "KubeVirt + node HA", "virt", "VM restart depends on node/machine health; not vSphere HA.",
                           "Combine MachineHealthChecks with VM runStrategy.", "Medium", "Admission control differs from vSphere HA."),
        "VCF-03-F05": feat(PARTIAL, "ResourceQuotas", "ocp", "Namespaces quotas, not resource pools.",
                           "Use namespace quotas and LimitRanges.", "Low", "Pool model differs."),
        "VCF-03-F06": feat(FULL, "VirtualMachine CRs", "virt", "VM create, clone, snapshot (with CSI) supported."),
        "VCF-03-F07": feat(FULL, "Live migration", "virt", "Evacuate nodes via live migration / drain."),
        "VCF-04-F01": feat(PARTIAL, "ODF / CSI", "odf", "Shared storage via ODF/CSI, not vSAN datastore.",
                           "Provide RWX/RWO via ODF or certified CSI.", "Medium", "Datastore abstraction differs."),
        "VCF-04-F02": feat(PARTIAL, "StorageClasses", "odf", "StorageClasses vs SPBM.",
                           "Map policies to StorageClasses/volume modes.", "Medium", "VM disk policy UX differs."),
        "VCF-04-F03": feat(PARTIAL, "ODF", "odf", "Efficiency depends on ODF/Ceph features.",
                           "Enable ODF compression/encoding where licensed.", "Medium", "Not vSAN efficiency UI."),
        "VCF-04-F04": feat(PARTIAL, "ODF / Ceph", "odf", "Replication/rebuild via Ceph.",
                           "Configure ODF failure domains.", "Medium", "Fault-domain model differs from vSAN."),
        "VCF-04-F05": feat(PARTIAL, "ODF DR", "odf", "Regional DR patterns, not vSAN stretch.",
                           "Use Regional DR / mirroring where supported.", "High", "Stretch design is different."),
        "VCF-04-F06": feat(PARTIAL, "NFS / ODF", "odf", "File via NFS CSI or ODF file.",
                           "Deploy NFS provisioner or ODF file.", "Medium", "Supplemental file services are add-on."),
        "VCF-04-F07": feat(PARTIAL, "ODF must-gather", "odf", "must-gather/health, not vSAN support bundles.",
                           "Use must-gather and ODF dashboards.", "Low", "Supportability tooling differs."),
        "VCF-05-F01": feat(PARTIAL, "OVN-Kubernetes / NAD", "ovn", "NAD/localnet/OVN; not NSX segments.",
                           "Use NetworkAttachmentDefinitions and OVN overlay.", "Medium", "Segment model differs."),
        "VCF-05-F02": feat(PARTIAL, "OVN", "ovn", "OVN routing, not NSX T0/T1.",
                           "Design OVN logical routers / UDN.", "High", "No Tier-0/1 construct."),
        "VCF-05-F03": feat(PARTIAL, "MetalLB / Ingress", "ovn", "LB via MetalLB/Ingress, not NSX Edge.",
                           "Deploy MetalLB or cloud LB plus ingress.", "Medium", "Edge services are composed."),
        "VCF-05-F04": feat(PARTIAL, "UDN / projects", "ovn", "Project/UDN isolation, not NSX VPC.",
                           "Use projects and User Defined Networks.", "Medium", "Tenant networking differs."),
        "VCF-05-F05": feat(PARTIAL, "OVN", "ovn", "Geneve overlay; underlay is admin-owned.",
                           "Validate MTU/Geneve per OpenShift networking.", "Medium", "No NSX TZ operational model."),
        "VCF-05-F06": feat(PARTIAL, "CoreDNS / NMState", "ocp", "CoreDNS and NMState DHCP patterns.",
                           "Use CoreDNS and NMState for host networking.", "Low", "IPAM is less NSX-like."),
        "VCF-05-F07": feat(PARTIAL, "OVN tracing", "ovn", "ovn-trace / Network Observability operator.",
                           "Install Network Observability operator.", "Medium", "Traceflow-class UX is different."),
        "VCF-06-F01": feat(PARTIAL, "NetworkPolicy / AdminNetworkPolicy", "ovn", "K8s NetworkPolicy, not NSX DFW.",
                           "Use AdminNetworkPolicy and baseline deny.", "High", "L4/L7 DFW depth lower than NSX."),
        "VCF-06-F02": feat(PARTIAL, "Ingress / egress firewall", "ovn", "EgressFirewall / Ingress controls.",
                           "Configure EgressFirewall and ingress ACLs.", "Medium", "Not NSX gateway firewall."),
        "VCF-06-F03": feat(FULL, "Labels / selectors", "ocp", "Dynamic grouping via labels is native."),
        "VCF-06-F04": feat(PARTIAL, "ACS", "acs", "Advanced Cluster Security for threat/policy.",
                           "Deploy RHACS for runtime/vulnerability controls.", "High", "IDS/IPS-class depends on ACS."),
        "VCF-06-F05": feat(PARTIAL, "SSO / ACS", "ocp", "Identity via SSO; limited identity firewall.",
                           "Bind SSO groups to NetworkPolicies/ACS.", "High", "Not NSX identity firewall."),
        "VCF-06-F06": feat(PARTIAL, "GitOps", "gitops", "Policy as code.",
                           "Stage NetworkPolicy via GitOps PRs.", "Medium", "Rollback is Git revert."),
        "VCF-06-F07": feat(PARTIAL, "ACS / Compliance operator", "acs", "Compliance reports via ACS/Compliance operator.",
                           "Export ACS compliance evidence.", "Medium", "Format differs from NSX."),
        "VCF-07-F01": feat(FULL, "Monitoring stack", "monitor", "Prometheus/Grafana in-cluster monitoring."),
        "VCF-07-F02": feat(PARTIAL, "Logging operator", "monitor", "Cluster logging; often Loki/ES.",
                           "Install OpenShift Logging / Loki.", "Medium", "Not Aria Logs."),
        "VCF-07-F03": feat(PARTIAL, "Prometheus", "monitor", "Capacity via metrics; less Aria planning.",
                           "Use Prometheus + ACM observability.", "Medium", "Forecasting is custom."),
        "VCF-07-F04": feat(PARTIAL, "Compliance / Policy", "acm", "Policy/compliance operators.",
                           "Use Compliance Operator and ACM policies.", "Medium", "Content differs from Aria."),
        "VCF-07-F05": feat(PARTIAL, "Service Mesh / labels", "ocp", "App maps via mesh/ACM.",
                           "Use Service Mesh or ACM application topology.", "Medium", "Shallower than Aria."),
        "VCF-07-F06": feat(FULL, "Alertmanager", "monitor", "Alerting and receivers are standard."),
        "VCF-07-F07": feat(PARTIAL, "must-gather", "ocp", "Evidence via must-gather and dashboards.",
                           "Collect must-gather and Grafana exports.", "Low", "Ops evidence packs differ."),
        "VCF-08-F01": feat(PARTIAL, "Developer catalog", "ocp", "OperatorHub/catalog, not Aria catalog.",
                           "Publish Helm/Operators in catalog.", "Medium", "IaaS catalog differs."),
        "VCF-08-F02": feat(FULL, "GitOps / Helm / Templates", "gitops", "Templates and GitOps are first-class."),
        "VCF-08-F03": feat(PARTIAL, "Pipelines / ACM", "gitops", "Approvals via Pipelines/ITSM.",
                           "Use Tekton manual approval or ITSM gates.", "Medium", "Governance UX differs."),
        "VCF-08-F04": feat(FULL, "Operators / Jobs", "ocp", "Day-2 via Operators, CronJobs, Ansible."),
        "VCF-08-F05": feat(FULL, "Projects / RBAC", "ocp", "Multi-tenancy via projects and quotas."),
        "VCF-08-F06": feat(PARTIAL, "Webhooks / Pipelines", "gitops", "ITSM via webhooks.",
                           "Integrate ServiceNow with Pipelines.", "Medium", "Connectors are DIY."),
        "VCF-08-F07": feat(FULL, "Kubernetes APIs", "ocp", "Extensibility via CRDs, Operators, secrets."),
        "VCF-09-F01": feat(FULL, "OpenShift", "ocp", "Kubernetes cluster lifecycle is the product."),
        "VCF-09-F02": feat(FULL, "Projects", "ocp", "Namespaces/projects with quotas."),
        "VCF-09-F03": feat(FULL, "OVN / Services", "ovn", "Pod/Service/Ingress networking is native."),
        "VCF-09-F04": feat(FULL, "ODF / CSI", "odf", "Persistent volumes via CSI/ODF."),
        "VCF-09-F05": feat(FULL, "OpenShift internal registry / Quay", "ocp", "Integrated registry plus Quay option."),
        "VCF-09-F06": feat(FULL, "SCCs / PSA", "ocp", "SCCs, PSA, secrets management."),
        "VCF-09-F07": feat(FULL, "Developer console", "ocp", "Strong developer self-service UX."),
        "VCF-10-F01": feat(PARTIAL, "MTV", "mtv", "Migration Toolkit for Virtualization cold migrate.",
                           "Use MTV for cold VM import to OpenShift Virt.", "Medium", "Not HCX."),
        "VCF-10-F02": feat(PARTIAL, "MTV / live migration", "mtv", "Limited live cross-platform vs HCX.",
                           "Warm migrate with MTV where supported; intra-cluster live migrate after.", "High", "No HCX vMotion fabric."),
        "VCF-10-F03": feat(PARTIAL, "MTV warm migration", "mtv", "Warm/replication-assisted MTV plans.",
                           "Use MTV warm migration.", "Medium", "Not HCX RAV."),
        "VCF-10-F04": feat(NO, "N/A", "mtv", "No HCX-class L2 extension."),
        "VCF-10-F05": feat(PARTIAL, "MTV", "mtv", "Import VMs; no VCF converge.",
                           "Import existing VMs with MTV.", "High", "No VCF Import/Converge."),
        "VCF-10-F06": feat(PARTIAL, "MTV plans", "mtv", "Migration plans/waves in MTV.",
                           "Group VMs in MTV plans.", "Medium", "Wave ops less HCX-like."),
        "VCF-10-F07": feat(PARTIAL, "MTV", "mtv", "Keep source until cutover.",
                           "Define MTV cutover windows.", "Medium", "Rollback is process-driven."),
        "VCF-11-F01": feat(PARTIAL, "OADP / partners", "odf", "Backup via OADP/Velero/partners.",
                           "Deploy OADP or certified backup partners.", "Medium", "Not a built-in VCF backup product."),
        "VCF-11-F02": feat(PARTIAL, "OADP", "odf", "Restore via OADP.",
                           "Restore namespaces/VMs with OADP.", "Medium", "File-level restore depends on tool."),
        "VCF-11-F03": feat(PARTIAL, "ACM DR / ODF", "acm", "Regional DR patterns.",
                           "Use Regional DR for apps/VMs where supported.", "High", "Not SRM identical."),
        "VCF-11-F04": feat(PARTIAL, "OADP schedules", "odf", "RPO via backup schedules.",
                           "Define backup schedules and test restores.", "Medium", "SLA dashboards custom."),
        "VCF-11-F05": feat(PARTIAL, "Object lock / partners", "odf", "Immutability via object storage lock.",
                           "Use S3 object lock with OADP.", "High", "Cyber recovery is design-heavy."),
        "VCF-11-F06": feat(PARTIAL, "CSI snapshots", "odf", "App consistency via snapshots/hooks.",
                           "Use freeze hooks and CSI snapshots.", "Medium", "DB agents are partner/DIY."),
        "VCF-11-F07": feat(PARTIAL, "OADP / ACM", "acm", "DR test evidence is operational.",
                           "Export backup/DR test logs.", "Medium", "Reporting is lighter."),
        "VCF-12-F01": feat(PARTIAL, "NVIDIA GPU Operator", "ocp", "GPU enablement on OpenShift.",
                           "Install GPU Operator and time-slicing/MIG.", "Medium", "Not VCF Private AI SKU."),
        "VCF-12-F02": feat(PARTIAL, "OpenShift AI", "rhoai", "Model serving via OpenShift AI / KServe.",
                           "Deploy RHOAI model servers.", "Medium", "Packaging differs from VCF Private AI."),
        "VCF-12-F03": feat(PARTIAL, "OpenShift AI", "rhoai", "Data science pipelines / RAG assembled on platform.",
                           "Build RAG with RHOAI pipelines and vector DBs.", "High", "Not a single VCF Private AI product."),
        "VCF-12-F04": feat(PARTIAL, "OpenShift AI", "rhoai", "MLOps via RHOAI/KServe, not VCF Private AI Services.",
                           "Use RHOAI model versions and serving.", "Medium", "Lifecycle UX differs."),
        "VCF-12-F05": feat(PARTIAL, "Projects / RBAC", "ocp", "Project RBAC for AI workspaces.",
                           "Isolate AI projects with quotas.", "Low", "AI-specific governance is limited."),
        "VCF-12-F06": feat(PARTIAL, "OpenShift platform", "ocp", "Uses platform identity/network/storage/monitoring.",
                           "Run AI on the same OCP stack.", "Low", "Integration is native K8s, not VCF services."),
        "VCF-12-F07": feat(PARTIAL, "Disconnected OpenShift", "ocp", "Air-gapped clusters support private inference.",
                           "Disconnected install plus egress NetworkPolicy.", "Medium", "Sovereign design is operational."),
    }
    return table[fid]


def openstack(pid, fid, name):
    table = {
        "VCF-01-F01": feat(PARTIAL, "Horizon / Placement", "nova", "Host/aggregate inventory, not VCF fleet domains.",
                           "Use Horizon/Placement and host aggregates.", "Medium", "No workload-domain object."),
        "VCF-01-F02": feat(NO, "N/A", "nova", "No VCF Workload Domain lifecycle."),
        "VCF-01-F03": feat(PARTIAL, "Nova", "nova", "Compute node add/remove is operational, not VCF cluster composition UI.",
                           "Scale compute hosts and aggregates.", "Medium", "Cluster composition is DIY."),
        "VCF-01-F04": feat(PARTIAL, "Keystone / cells", "keystone", "Isolation via projects/cells, not VCF domains.",
                           "Separate service projects and cells.", "High", "Management domain analogue is weak."),
        "VCF-01-F05": feat(PARTIAL, "Ironic / distro installer", "ironic", "Bare metal via Ironic or distro tools.",
                           "Commission with Ironic or vendor installer.", "High", "Not VCF commissioning."),
        "VCF-01-F06": feat(PARTIAL, "Config management", "heat", "Baselines via Ansible/Heat, not VCF.",
                           "Enforce desired state with Ansible.", "High", "No SDDC Manager baselines."),
        "VCF-01-F07": feat(PARTIAL, "Availability zones", "nova", "AZs/regions, not stretch domains.",
                           "Model sites as AZs/regions.", "High", "Stretch semantics differ."),
        "VCF-02-F01": feat(PARTIAL, "Distro installer", "docs", "Bring-up is distro-specific (kolla/OSA/tripleo-class).",
                           "Use chosen OpenStack distro installer.", "High", "Not VCF Installer."),
        "VCF-02-F02": feat(NO, "N/A", "docs", "No SDDC Manager."),
        "VCF-02-F03": feat(PARTIAL, "Distro repos", "docs", "Package repos, not VCF depot.",
                           "Mirror distro/OpenStack repos.", "Medium", "No VCF bundle integrity model."),
        "VCF-02-F04": feat(PARTIAL, "Distro tooling", "docs", "Upgrade prechecks are distro-specific.",
                           "Follow distro upgrade validation guides.", "High", "No standard VCF precheck pack."),
        "VCF-02-F05": feat(NO, "N/A", "docs", "No coordinated VCF-style full-stack upgrade product."),
        "VCF-02-F06": feat(PARTIAL, "Distro", "docs", "Selective service upgrades with high risk.",
                           "Upgrade services per distro skip-level guidance.", "High", "Skip-level is operator-owned."),
        "VCF-02-F07": feat(PARTIAL, "Distro", "docs", "Rollback is restore/reinstall.",
                           "Snapshot control plane; document rollback limits.", "High", "Weak rollback posture."),
        "VCF-03-F01": feat(FULL, "Nova / KVM / libvirt", "nova", "Nova on KVM provides VM compute."),
        "VCF-03-F02": feat(FULL, "Horizon / APIs", "horizon", "Central inventory, Keystone RBAC, REST APIs."),
        "VCF-03-F03": feat(PARTIAL, "Nova scheduler / Watcher", "nova", "Scheduler filters, not DRS.",
                           "Tune scheduler filters/weights; optional Watcher.", "Medium", "No DRS equivalent."),
        "VCF-03-F04": feat(PARTIAL, "Nova HA / masakari", "nova", "Instance HA via masakari/design.",
                           "Deploy masakari or pacemaker instance HA.", "High", "Not vSphere HA."),
        "VCF-03-F05": feat(PARTIAL, "Nova quotas", "nova", "Project quotas, not resource pools.",
                           "Use project quotas and flavors.", "Low", "Pool model differs."),
        "VCF-03-F06": feat(FULL, "Nova", "nova", "Boot, snapshot, image-based clone are core."),
        "VCF-03-F07": feat(PARTIAL, "Nova live migration", "nova", "Live migration/maintenance; host remediation DIY.",
                           "Use live migration and disable-compute.", "Medium", "Remediation is less automated."),
        "VCF-04-F01": feat(FULL, "Cinder", "cinder", "Block storage volumes for instances."),
        "VCF-04-F02": feat(PARTIAL, "Cinder types", "cinder", "Volume types vs SPBM.",
                           "Map extra-specs to volume types.", "Medium", "VM-disk policy UX differs."),
        "VCF-04-F03": feat(PARTIAL, "Backend", "cinder", "Efficiency depends on Ceph/backend.",
                           "Use Ceph compression/EC if backend supports.", "Medium", "Not vSAN efficiency UI."),
        "VCF-04-F04": feat(PARTIAL, "Ceph / backend", "cinder", "Resilience is backend-specific.",
                           "Design Ceph CRUSH/failure domains.", "Medium", "Not vSAN fault domains UI."),
        "VCF-04-F05": feat(PARTIAL, "Ceph stretch / Cinder replication", "cinder", "Stretch is design-heavy.",
                           "Use Ceph stretch or volume replication.", "High", "Not vSAN stretch."),
        "VCF-04-F06": feat(PARTIAL, "Manila", "manila", "Shared file via Manila.",
                           "Deploy Manila with NFS/CephFS.", "Medium", "Add-on vs integrated vSAN File."),
        "VCF-04-F07": feat(PARTIAL, "Backend tooling", "cinder", "Health via Ceph/cinder logs.",
                           "Use Ceph dashboard and cinder service status.", "Medium", "Support bundles are DIY."),
        "VCF-05-F01": feat(FULL, "Neutron", "neutron", "Networks/ports/security groups."),
        "VCF-05-F02": feat(PARTIAL, "Neutron routers", "neutron", "Neutron routers, not NSX T0/T1.",
                           "Map T0/T1 to Neutron routers/provider nets.", "High", "Taxonomy differs."),
        "VCF-05-F03": feat(PARTIAL, "Octavia / Neutron", "octavia", "LB via Octavia; NAT via Neutron.",
                           "Deploy Octavia and floating IPs.", "Medium", "Not NSX Edge."),
        "VCF-05-F04": feat(PARTIAL, "Neutron RBAC", "neutron", "Project networks as tenancy.",
                           "Use project networks and RBAC shares.", "Medium", "Not NSX VPC."),
        "VCF-05-F05": feat(PARTIAL, "ML2/OVS/OVN", "neutron", "Overlay via Geneve/VXLAN.",
                           "Validate underlay MTU for Geneve/VXLAN.", "Medium", "Ops model differs from NSX."),
        "VCF-05-F06": feat(FULL, "Neutron DHCP / Designate", "neutron", "DHCP built-in; DNS via Designate."),
        "VCF-05-F07": feat(PARTIAL, "Neutron logs", "neutron", "Basic observability; tracing DIY.",
                           "Use Neutron logging and TAP services.", "High", "No NSX Traceflow."),
        "VCF-06-F01": feat(PARTIAL, "Security groups", "neutron", "Security groups are L3/L4, not NSX DFW.",
                           "Use SG plus optional FWaaS/OVN ACLs.", "High", "East-west DFW incomplete."),
        "VCF-06-F02": feat(PARTIAL, "FWaaS / SG", "neutron", "North-south via FWaaS/router ACLs.",
                           "Enable FWaaS or perimeter NVA.", "High", "Not NSX gateway firewall."),
        "VCF-06-F03": feat(PARTIAL, "SG / tags", "neutron", "Limited dynamic grouping.",
                           "Use port tags and automation to sync SGs.", "High", "Weaker than NSX groups."),
        "VCF-06-F04": feat(NO, "N/A", "neutron", "No native IDS/IPS product in core OpenStack."),
        "VCF-06-F05": feat(PARTIAL, "Keystone", "keystone", "Identity for APIs, not packet identity firewall.",
                           "Combine Keystone with SG automation.", "High", "Not NSX identity firewall."),
        "VCF-06-F06": feat(PARTIAL, "Heat / Ansible", "heat", "Policy as automation.",
                           "Manage SG/FWaaS via IaC.", "Medium", "No NSX publish/rollback UI."),
        "VCF-06-F07": feat(PARTIAL, "Barbican / audit", "keystone", "Audit via CADF/logs.",
                           "Export CADF and Neutron logs.", "High", "Compliance reporting is DIY."),
        "VCF-07-F01": feat(PARTIAL, "Ceilometer / Prometheus", "telemetry", "Telemetry stack is composed.",
                           "Deploy Prometheus/Ceilometer as designed.", "Medium", "Not Aria out of box."),
        "VCF-07-F02": feat(PARTIAL, "ELK / distro logging", "telemetry", "Logs via distro ELK.",
                           "Centralize service logs in ELK/Loki.", "Medium", "Not Aria Logs."),
        "VCF-07-F03": feat(PARTIAL, "Watcher / Gnocchi", "telemetry", "Capacity via Watcher/custom.",
                           "Use Watcher or custom capacity jobs.", "High", "Planning maturity varies."),
        "VCF-07-F04": feat(PARTIAL, "Ansible / Inspector", "ironic", "Compliance DIY.",
                           "Scan with OpenSCAP/Inspector.", "High", "No Aria compliance packs."),
        "VCF-07-F05": feat(NO, "N/A", "telemetry", "No first-class app dependency mapping product."),
        "VCF-07-F06": feat(PARTIAL, "Aodh / Alertmanager", "telemetry", "Alerting composed.",
                           "Wire Aodh or Alertmanager.", "Medium", "Routing is custom."),
        "VCF-07-F07": feat(PARTIAL, "Horizon", "horizon", "Basic reports; evidence DIY.",
                           "Export Horizon/usage data.", "Medium", "Ops evidence packs are custom."),
        "VCF-08-F01": feat(PARTIAL, "Horizon / Heat", "heat", "Self-service via Horizon, not Aria catalog.",
                           "Publish Heat/Trove templates in Horizon.", "Medium", "Catalog UX differs."),
        "VCF-08-F02": feat(FULL, "Heat / Terraform", "heat", "Templates are first-class."),
        "VCF-08-F03": feat(PARTIAL, "Keystone / ITSM", "keystone", "Approvals via ITSM outside OpenStack.",
                           "Gate Heat stacks with ITSM.", "High", "No native approval engine."),
        "VCF-08-F04": feat(PARTIAL, "Heat / Mistral", "heat", "Day-2 via Heat update/Mistral.",
                           "Encode day-2 as Heat/Mistral/Ansible.", "Medium", "Less packaged than Aria."),
        "VCF-08-F05": feat(FULL, "Keystone projects", "keystone", "Multi-tenancy is core."),
        "VCF-08-F06": feat(PARTIAL, "APIs", "horizon", "ITSM via APIs.",
                           "Integrate via REST/webhooks.", "Medium", "Connectors DIY."),
        "VCF-08-F07": feat(FULL, "REST APIs", "horizon", "Extensible APIs and credential stores (Barbican)."),
        "VCF-09-F01": feat(PARTIAL, "Magnum / external K8s", "magnum", "Magnum COE optional; often external Kubernetes.",
                           "Use Magnum or attach external K8s.", "High", "Not vSphere Supervisor."),
        "VCF-09-F02": feat(PARTIAL, "Kubernetes", "magnum", "Namespaces if K8s is present.",
                           "Operate namespaces on Magnum/external K8s.", "Medium", "Depends on Magnum adoption."),
        "VCF-09-F03": feat(PARTIAL, "K8s CNI", "magnum", "CNI chosen by K8s distro.",
                           "Use Calico/OVN on the K8s layer.", "Medium", "Not NSX-VKS."),
        "VCF-09-F04": feat(PARTIAL, "Cinder CSI", "cinder", "CSI to Cinder if K8s present.",
                           "Install Cinder CSI.", "Medium", "Depends on K8s being in scope."),
        "VCF-09-F05": feat(PARTIAL, "Glance / external registry", "glance", "Images in Glance; container registry external.",
                           "Deploy Harbor/Quay alongside.", "Medium", "Not integrated VCF registry."),
        "VCF-09-F06": feat(PARTIAL, "K8s PSS", "magnum", "Pod security if K8s present.",
                           "Apply PSS/OPA on the K8s cluster.", "High", "Not a platform default."),
        "VCF-09-F07": feat(PARTIAL, "Horizon", "horizon", "Limited developer K8s UX vs OpenShift.",
                           "Expose kubectl via Magnum certs.", "High", "Developer experience is weaker."),
        "VCF-10-F01": feat(PARTIAL, "Glance / virt-v2v", "glance", "Import images/cold migrate.",
                           "Convert disks with virt-v2v into Glance.", "High", "Not HCX."),
        "VCF-10-F02": feat(PARTIAL, "Nova live migration", "nova", "Live migrate within cloud only.",
                           "Live migrate intra-cloud; cross-platform is cutover.", "High", "No HCX fabric."),
        "VCF-10-F03": feat(PARTIAL, "Cinder replication", "cinder", "Replication-assisted if backend supports.",
                           "Use volume replication then rebuild instance.", "High", "Not HCX RAV."),
        "VCF-10-F04": feat(NO, "N/A", "neutron", "No HCX L2 extension product."),
        "VCF-10-F05": feat(NO, "N/A", "docs", "No VCF Import/Converge."),
        "VCF-10-F06": feat(PARTIAL, "Process", "docs", "Wave ops are project-managed.",
                           "Track waves outside the platform.", "High", "No HCX wave console."),
        "VCF-10-F07": feat(PARTIAL, "Process", "docs", "Keep source until cutover.",
                           "Define rollback windows operationally.", "Medium", "Process-driven."),
        "VCF-11-F01": feat(PARTIAL, "Freezer / distro backup", "cinder", "Backup via Freezer/partners/Ceph RBD mirror.",
                           "Deploy backup project or Ceph RBD mirror.", "High", "Not a unified VCF backup product."),
        "VCF-11-F02": feat(PARTIAL, "Cinder backup", "cinder", "Volume backup/restore.",
                           "Use cinder-backup to object store.", "Medium", "File-level restore limited."),
        "VCF-11-F03": feat(PARTIAL, "Cinder / Masakari", "cinder", "DR is designed, not a product suite.",
                           "Orchestrate failover with Heat/Ansible.", "High", "Not SRM."),
        "VCF-11-F04": feat(PARTIAL, "Backend RPO", "cinder", "RPO depends on backend.",
                           "Document backend RPO/RTO.", "High", "No native SLA console."),
        "VCF-11-F05": feat(PARTIAL, "Object lock", "cinder", "Immutability if object store supports it.",
                           "Use S3 object lock for backups.", "High", "Cyber recovery DIY."),
        "VCF-11-F06": feat(PARTIAL, "Guest agents", "nova", "App-consistent via guest fsfreeze/QEMU guest agent.",
                           "Use guest agent freeze plus volume backup.", "Medium", "DB agents DIY."),
        "VCF-11-F07": feat(PARTIAL, "Process", "horizon", "Reporting DIY.",
                           "Export backup job logs.", "High", "Evidence packs custom."),
        "VCF-12-F01": feat(PARTIAL, "Nova PCI passthrough", "nova", "GPU passthrough/vGPU if configured.",
                           "Enable PCI alias / vGPU types.", "High", "Not VCF Private AI."),
        "VCF-12-F02": feat(NO, "N/A", "docs", "No first-class model serving product."),
        "VCF-12-F03": feat(NO, "N/A", "docs", "No RAG platform product."),
        "VCF-12-F04": feat(NO, "N/A", "docs", "No MLOps product."),
        "VCF-12-F05": feat(PARTIAL, "Keystone", "keystone", "Generic project RBAC only.",
                           "Isolate GPU flavors by project.", "Medium", "No AI governance product."),
        "VCF-12-F06": feat(PARTIAL, "Nova/Cinder/Neutron", "nova", "AI VMs use core IaaS.",
                           "Run GPU instances on KVM.", "Medium", "DIY vs VCF Private AI."),
        "VCF-12-F07": feat(PARTIAL, "On-prem cloud", "docs", "On-prem possible; egress operator-owned.",
                           "Keep inference on-prem; restrict Neutron egress.", "Medium", "Sovereign controls are design-only."),
    }
    return table[fid]


def proxmox(pid, fid, name):
    table = {
        "VCF-01-F01": feat(PARTIAL, "Proxmox datacenter view", "pve", "Cluster/node inventory in PVE UI, not VCF fleet domains.",
                           "Use Datacenter/cluster tree.", "Low", "No workload-domain object."),
        "VCF-01-F02": feat(NO, "N/A", "pve", "No VCF Workload Domain lifecycle."),
        "VCF-01-F03": feat(FULL, "pvecm", "pve", "Add/remove cluster nodes is a core PVE operation."),
        "VCF-01-F04": feat(NO, "N/A", "pve", "No principal vs workload domain separation product."),
        "VCF-01-F05": feat(PARTIAL, "Debian / installer ISO", "pve", "ISO install, not VCF commissioning.",
                           "Install nodes from PVE ISO and join cluster.", "Medium", "Hardware HCL process differs."),
        "VCF-01-F06": feat(PARTIAL, "Config files", "pve", "Baselines are file-based (/etc/pve).",
                           "Version /etc/pve with Git; no SDDC baselines.", "High", "Drift tooling is DIY."),
        "VCF-01-F07": feat(PARTIAL, "Ceph stretch / qdevice", "ceph", "Multi-site via Ceph stretch or separate clusters.",
                           "Design Ceph stretch or dual clusters.", "High", "Not VCF stretch domains."),
        "VCF-02-F01": feat(PARTIAL, "PVE installer", "pve", "Simple ISO installer, not VCF Installer.",
                           "Use PVE ISO bring-up.", "Low", "No VCF prerequisite engine."),
        "VCF-02-F02": feat(NO, "N/A", "pve", "No SDDC Manager."),
        "VCF-02-F03": feat(PARTIAL, "apt / enterprise repo", "pve", "apt repositories, not VCF depot.",
                           "Use enterprise apt repos or offline mirrors.", "Low", "No VCF bundle model."),
        "VCF-02-F04": feat(PARTIAL, "apt", "pve", "Limited prechecks vs VCF.",
                           "Test upgrades on a node; read release notes.", "Medium", "No structured precheck report."),
        "VCF-02-F05": feat(PARTIAL, "apt + reboot", "pve", "Rolling node upgrades, not VCF stack.",
                           "Upgrade nodes rolling with live migration.", "Medium", "No coordinated NSX/vSAN-class stack."),
        "VCF-02-F06": feat(PARTIAL, "apt pinning", "pve", "Selective packages via apt.",
                           "Hold packages; upgrade selected nodes.", "Medium", "Not VCF skip-level."),
        "VCF-02-F07": feat(PARTIAL, "apt history", "pve", "Rollback often snapshot/reinstall.",
                           "Snapshot boot disk before upgrade.", "High", "Limited rollback."),
        "VCF-03-F01": feat(FULL, "KVM", "pve", "KVM/QEMU VM compute is the product."),
        "VCF-03-F02": feat(FULL, "Proxmox VE GUI/API", "pve", "Central UI, RBAC, REST API."),
        "VCF-03-F03": feat(PARTIAL, "HA groups / affinity", "pve", "HA groups, not DRS.",
                           "Use HA groups and manual placement.", "Medium", "No automated load-balancing DRS."),
        "VCF-03-F04": feat(FULL, "PVE HA", "pve", "HA manager restarts VMs on node failure."),
        "VCF-03-F05": feat(PARTIAL, "CPU/memory limits", "pve", "VM resource limits, not resource pools.",
                           "Set VM cpulimit/balloon and pools.", "Low", "Pool semantics differ."),
        "VCF-03-F06": feat(FULL, "QEMU", "pve", "Create, clone, snapshot/rollback are core."),
        "VCF-03-F07": feat(FULL, "Live migration", "pve", "Maintenance via live migration."),
        "VCF-04-F01": feat(FULL, "Ceph / ZFS / LVM", "ceph", "Shared or replicated storage for VMs (Ceph common)."),
        "VCF-04-F02": feat(PARTIAL, "Storage classes in PVE", "pve", "Storage definitions, not SPBM.",
                           "Map policies to storage IDs (Ceph/ZFS).", "Medium", "No VM-level SPBM."),
        "VCF-04-F03": feat(PARTIAL, "ZFS / Ceph", "ceph", "Compression/dedup depend on backend.",
                           "Enable ZFS compression or Ceph features.", "Medium", "Not vSAN efficiency UI."),
        "VCF-04-F04": feat(PARTIAL, "Ceph", "ceph", "CRUSH/failure domains if Ceph used.",
                           "Configure Ceph CRUSH map.", "Medium", "Ops model differs from vSAN."),
        "VCF-04-F05": feat(PARTIAL, "Ceph stretch", "ceph", "Stretch Ceph is advanced.",
                           "Design stretch Ceph with tie-breaker.", "High", "Not vSAN stretch wizard."),
        "VCF-04-F06": feat(PARTIAL, "ZFS / NFS", "pve", "File via NFS/CIFS storage.",
                           "Add NFS or ZFS datasets as storage.", "Low", "Not vSAN File Services."),
        "VCF-04-F07": feat(PARTIAL, "Ceph dashboard / PVE", "ceph", "Health in PVE/Ceph.",
                           "Use PVE Ceph UI and ceph -s.", "Low", "Support bundles are logs."),
        "VCF-05-F01": feat(PARTIAL, "Linux bridges / SDN", "sdn", "VNets/zones in PVE SDN; not NSX segments.",
                           "Use PVE SDN zones/VNets or VLANs.", "Medium", "Segment model simpler than NSX."),
        "VCF-05-F02": feat(PARTIAL, "FRR / SDN", "sdn", "Simple routing via FRR EVPN optional.",
                           "Enable EVPN-VXLAN SDN if required.", "High", "No T0/T1."),
        "VCF-05-F03": feat(NO, "N/A", "sdn", "No NSX Edge / advanced gateway services product."),
        "VCF-05-F04": feat(PARTIAL, "SDN zones", "sdn", "Limited multi-tenant SDN.",
                           "Isolate with VNets/VLANs.", "High", "Not NSX VPC."),
        "VCF-05-F05": feat(PARTIAL, "VXLAN/EVPN", "sdn", "Optional overlay.",
                           "Validate underlay if using VXLAN.", "High", "Optional and simpler than NSX."),
        "VCF-05-F06": feat(PARTIAL, "dnsmasq", "sdn", "Simple IPAM/DHCP in SDN.",
                           "Use PVE SDN IPAM or external DHCP.", "Low", "IPAM is basic."),
        "VCF-05-F07": feat(PARTIAL, "PVE", "pve", "Basic NIC/bridge status.",
                           "Use tcpdump and PVE graphs.", "Medium", "No Traceflow."),
        "VCF-06-F01": feat(NO, "N/A", "pve", "No distributed firewall equivalent to NSX DFW."),
        "VCF-06-F02": feat(PARTIAL, "Host firewall", "pve", "Datacenter/host firewall only.",
                           "Use PVE firewall plus external NGFW.", "High", "Not NSX gateway FW."),
        "VCF-06-F03": feat(PARTIAL, "Firewall aliases", "pve", "Aliases/IPSets, not dynamic NSX groups.",
                           "Maintain IPSets/aliases.", "High", "No tag-based DFW groups."),
        "VCF-06-F04": feat(NO, "N/A", "pve", "No IDS/IPS product."),
        "VCF-06-F05": feat(NO, "N/A", "pve", "No identity-aware firewall."),
        "VCF-06-F06": feat(PARTIAL, "Cluster firewall options", "pve", "Firewall config replication.",
                           "Manage firewall via API/Git.", "Medium", "Limited change-control UX."),
        "VCF-06-F07": feat(NO, "N/A", "pve", "No NSX-class security posture reporting."),
        "VCF-07-F01": feat(PARTIAL, "PVE graphs / metrics", "pve", "Built-in graphs; not Aria.",
                           "Use PVE metrics or external Prometheus.", "Medium", "Monitoring depth is basic."),
        "VCF-07-F02": feat(PARTIAL, "syslog", "pve", "Syslog forwarding.",
                           "Forward syslog to SIEM.", "Medium", "No Aria Logs."),
        "VCF-07-F03": feat(PARTIAL, "PVE", "pve", "Capacity is operator-reviewed.",
                           "Export RRD/metrics; plan manually.", "High", "No Aria capacity engine."),
        "VCF-07-F04": feat(NO, "N/A", "pve", "No configuration compliance product."),
        "VCF-07-F05": feat(NO, "N/A", "pve", "No application dependency mapping."),
        "VCF-07-F06": feat(PARTIAL, "email / gotify", "pve", "Simple notifications.",
                           "Configure notification targets.", "Low", "Limited routing/suppression."),
        "VCF-07-F07": feat(PARTIAL, "PVE", "pve", "Basic task logs.",
                           "Export task/HA logs.", "Medium", "Evidence packs DIY."),
        "VCF-08-F01": feat(PARTIAL, "API / Terraform", "api", "No Aria catalog; API/Terraform self-service.",
                           "Expose Terraform/API to consumers.", "Medium", "No service catalog UI."),
        "VCF-08-F02": feat(PARTIAL, "Terraform / snippets", "api", "Cloud-init/snippets as templates.",
                           "Use cloud-init and Terraform providers.", "Medium", "Weaker than Aria templates."),
        "VCF-08-F03": feat(NO, "N/A", "api", "No native approval workflow product."),
        "VCF-08-F04": feat(PARTIAL, "API / hooks", "api", "Day-2 via API/hooks.",
                           "Script day-2 with API.", "Medium", "Not a catalog of day-2 actions."),
        "VCF-08-F05": feat(PARTIAL, "Pools / ACL", "pve", "Pools and ACLs as tenancy.",
                           "Use pools plus user ACLs.", "Medium", "Weaker than Aria projects."),
        "VCF-08-F06": feat(PARTIAL, "API", "api", "ITSM via API.",
                           "Call PVE API from pipelines.", "Medium", "No native ITSM pack."),
        "VCF-08-F07": feat(PARTIAL, "API tokens", "api", "API tokens; secret management DIY.",
                           "Use API tokens and external vault.", "Medium", "Extensibility is API-level."),
        "VCF-09-F01": feat(NO, "N/A", "pve", "No vSphere Kubernetes Service / Supervisor equivalent (LXC is not K8s lifecycle)."),
        "VCF-09-F02": feat(NO, "N/A", "pve", "No Kubernetes namespace tenancy product."),
        "VCF-09-F03": feat(NO, "N/A", "pve", "No platform pod/service networking."),
        "VCF-09-F04": feat(NO, "N/A", "pve", "No CSI platform for Supervisor-class K8s."),
        "VCF-09-F05": feat(NO, "N/A", "pve", "No integrated registry/content service."),
        "VCF-09-F06": feat(NO, "N/A", "pve", "No K8s platform security controls."),
        "VCF-09-F07": feat(NO, "N/A", "pve", "No K8s developer self-service platform."),
        "VCF-10-F01": feat(PARTIAL, "qm import", "pve", "Import disks/OVA-like via qemu-img.",
                           "Convert and import VM disks.", "Medium", "Not HCX."),
        "VCF-10-F02": feat(PARTIAL, "Live migration", "pve", "Intra-cluster only.",
                           "Live migrate within cluster; cross-platform cutover.", "High", "No HCX fabric."),
        "VCF-10-F03": feat(PARTIAL, "Replication", "pve", "Async replication between nodes.",
                           "Use PVE replication then cutover.", "Medium", "Not HCX RAV."),
        "VCF-10-F04": feat(NO, "N/A", "pve", "No L2 network extension product."),
        "VCF-10-F05": feat(NO, "N/A", "pve", "No VCF Import/Converge."),
        "VCF-10-F06": feat(PARTIAL, "Process", "pve", "Waves are project-managed.",
                           "Track migrations in a runbook.", "High", "No wave console."),
        "VCF-10-F07": feat(PARTIAL, "Snapshots", "pve", "Rollback via snapshots if pre-cutover.",
                           "Snapshot before conversion; keep source.", "Medium", "Process-driven."),
        "VCF-11-F01": feat(FULL, "Proxmox Backup Server", "pbs", "PBS provides VM/CT backup."),
        "VCF-11-F02": feat(FULL, "PBS", "pbs", "Restore VMs/files from PBS."),
        "VCF-11-F03": feat(PARTIAL, "Replication / PBS offsite", "pbs", "DR via offsite PBS/replication, not SRM.",
                           "Replicate PBS datastore offsite; document failover.", "Medium", "No recovery-plan orchestrator."),
        "VCF-11-F04": feat(PARTIAL, "PBS schedules", "pbs", "Backup jobs encode RPO.",
                           "Define job schedules and verify restores.", "Low", "RTO is operational."),
        "VCF-11-F05": feat(PARTIAL, "PBS prune/verify", "pbs", "Limited immutability vs enterprise cyber vaults.",
                           "Use PBS namespaces and offsite copies.", "High", "Cyber recovery is design-limited."),
        "VCF-11-F06": feat(PARTIAL, "QEMU guest agent", "pve", "fsfreeze via guest agent.",
                           "Install QEMU guest agent for consistent snapshots.", "Low", "DB-aware agents limited."),
        "VCF-11-F07": feat(PARTIAL, "PBS", "pbs", "Job logs/verify tasks.",
                           "Export PBS task logs as evidence.", "Low", "Reporting is basic."),
        "VCF-12-F01": feat(PARTIAL, "PCI passthrough", "pve", "GPU passthrough supported.",
                           "Configure IOMMU and PCI passthrough.", "Medium", "Not VCF Private AI."),
        "VCF-12-F02": feat(NO, "N/A", "pve", "No model-serving platform product."),
        "VCF-12-F03": feat(NO, "N/A", "pve", "No RAG platform."),
        "VCF-12-F04": feat(NO, "N/A", "pve", "No MLOps product."),
        "VCF-12-F05": feat(PARTIAL, "PVE ACL", "pve", "Generic ACL only.",
                           "Restrict GPU VMs with ACLs.", "Low", "No AI governance."),
        "VCF-12-F06": feat(PARTIAL, "PVE", "pve", "AI VMs use KVM/storage/network.",
                           "Run GPU VMs on PVE.", "Medium", "DIY."),
        "VCF-12-F07": feat(PARTIAL, "On-prem PVE", "pve", "On-prem by default.",
                           "Keep inference local; firewall egress.", "Low", "Sovereign by architecture, not a product."),
    }
    return table[fid]


PLATFORMS = [
    {
        "platformKey": "AzureLocal",
        "platformName": "Microsoft Azure Local",
        "evaluationBasisType": "ProductVersion",
        "evaluatedBaseline": "Azure Local (public Microsoft Learn / Azure Local documentation baseline, 2026-09)",
        "evidenceSource": "Microsoft Learn / Azure Local public documentation",
        "supportingComponents": ["Hyper-V", "Storage Spaces Direct", "Azure Arc", "Windows Admin Center"],
        "solutionComponents": [
            {"Component": "Hyper-V", "Role": "Hypervisor"},
            {"Component": "Storage Spaces Direct", "Role": "HCI storage"},
            {"Component": "Azure Arc", "Role": "Cloud control plane / inventory"},
            {"Component": "Windows Admin Center", "Role": "Cluster management UI"},
            {"Component": "AKS on Azure Local", "Role": "Kubernetes"},
        ],
        "disclaimer": "SME mapping of public Microsoft Azure Local documentation to CN v0.3 FeatureIDs. Evidence-Backed Draft only. Confirm Azure Local solution version and portal SKUs before advisory sign-off.",
        "evidenceCatalog": {
            "azureLocal": "https://learn.microsoft.com/en-us/azure/azure-local/",
            "deploy": "https://learn.microsoft.com/en-us/azure/azure-local/deploy/deployment-introduction",
            "hyperv": "https://learn.microsoft.com/en-us/windows-server/virtualization/hyper-v/hyper-v-on-windows-server",
            "s2d": "https://learn.microsoft.com/en-us/windows-server/storage/storage-spaces/storage-spaces-direct-overview",
            "wac": "https://learn.microsoft.com/en-us/windows-server/manage/windows-admin-center/overview",
            "arc": "https://learn.microsoft.com/en-us/azure/azure-arc/overview",
            "sdn": "https://learn.microsoft.com/en-us/azure/azure-local/concepts/network-atc-overview",
            "security": "https://learn.microsoft.com/en-us/azure/defender-for-cloud/defender-for-cloud-introduction",
            "monitor": "https://learn.microsoft.com/en-us/azure/azure-monitor/overview",
            "aks": "https://learn.microsoft.com/en-us/azure/aks/aksarc/aks-overview",
            "migrate": "https://learn.microsoft.com/en-us/azure/migrate/migrate-services-overview",
            "backup": "https://learn.microsoft.com/en-us/azure/backup/backup-overview",
            "update": "https://learn.microsoft.com/en-us/azure/azure-local/update/about-updates",
        },
        "assign": azure,
    },
    {
        "platformKey": "OpenShiftVirtualization",
        "platformName": "Red Hat OpenShift Virtualization",
        "evaluationBasisType": "ProductVersion",
        "evaluatedBaseline": "OpenShift Virtualization on OpenShift Container Platform (public Red Hat docs baseline, 2026-09)",
        "evidenceSource": "Red Hat OpenShift / OpenShift Virtualization public documentation",
        "supportingComponents": ["OpenShift Container Platform", "KubeVirt", "OVN-Kubernetes", "OpenShift Data Foundation"],
        "solutionComponents": [
            {"Component": "OpenShift Virtualization", "Role": "KubeVirt VM platform"},
            {"Component": "OpenShift Container Platform", "Role": "Kubernetes control plane"},
            {"Component": "OVN-Kubernetes", "Role": "Cluster networking"},
            {"Component": "OpenShift Data Foundation", "Role": "Persistent storage"},
            {"Component": "Migration Toolkit for Virtualization", "Role": "VM migration"},
        ],
        "disclaimer": "SME mapping of public Red Hat OpenShift Virtualization documentation to CN v0.3 FeatureIDs. Evidence-Backed Draft only. Confirm OCP/Virt versions before advisory sign-off.",
        "evidenceCatalog": {
            "virt": "https://docs.redhat.com/en/documentation/openshift_container_platform/latest/html/virtualization/about-openshift-virtualization",
            "ocp": "https://docs.redhat.com/en/documentation/openshift_container_platform/latest",
            "install": "https://docs.redhat.com/en/documentation/openshift_container_platform/latest/html/installing",
            "upgrade": "https://docs.redhat.com/en/documentation/openshift_container_platform/latest/html/updating_clusters",
            "ovn": "https://docs.redhat.com/en/documentation/openshift_container_platform/latest/html/networking",
            "odf": "https://docs.redhat.com/en/documentation/red_hat_openshift_data_foundation",
            "acm": "https://docs.redhat.com/en/documentation/red_hat_advanced_cluster_management_for_kubernetes",
            "gitops": "https://docs.redhat.com/en/documentation/red_hat_openshift_gitops",
            "monitor": "https://docs.redhat.com/en/documentation/openshift_container_platform/latest/html/monitoring",
            "acs": "https://docs.redhat.com/en/documentation/red_hat_advanced_cluster_security_for_kubernetes",
            "mtv": "https://docs.redhat.com/en/documentation/migration_toolkit_for_virtualization",
            "rhoai": "https://docs.redhat.com/en/documentation/red_hat_openshift_ai",
        },
        "assign": openshift,
    },
    {
        "platformKey": "OpenStackKVM",
        "platformName": "OpenStack on KVM (composite)",
        "evaluationBasisType": "CompositePeriod",
        "evaluatedBaseline": "OpenStackKVM Composite — Evaluation Basis: Q3-2026 (Nova/Cinder/Neutron/KVM public docs; distro-agnostic)",
        "evidenceSource": "OpenStack official documentation (docs.openstack.org)",
        "supportingComponents": ["Nova", "Cinder", "Neutron", "Keystone", "Horizon", "KVM/libvirt"],
        "solutionComponents": [
            {"Component": "Nova", "Role": "Compute"},
            {"Component": "Cinder", "Role": "Block storage"},
            {"Component": "Neutron", "Role": "Networking"},
            {"Component": "Keystone", "Role": "Identity"},
            {"Component": "Horizon", "Role": "Dashboard"},
            {"Component": "Heat", "Role": "Orchestration"},
        ],
        "disclaimer": "Composite evaluation-period mapping of public OpenStack project docs to CN v0.3. Not a single product version. Distro (Red Hat, Canonical, vanilla) must be confirmed before advisory sign-off.",
        "evidenceCatalog": {
            "docs": "https://docs.openstack.org/",
            "nova": "https://docs.openstack.org/nova/latest/",
            "cinder": "https://docs.openstack.org/cinder/latest/",
            "neutron": "https://docs.openstack.org/neutron/latest/",
            "keystone": "https://docs.openstack.org/keystone/latest/",
            "horizon": "https://docs.openstack.org/horizon/latest/",
            "heat": "https://docs.openstack.org/heat/latest/",
            "glance": "https://docs.openstack.org/glance/latest/",
            "ironic": "https://docs.openstack.org/ironic/latest/",
            "octavia": "https://docs.openstack.org/octavia/latest/",
            "manila": "https://docs.openstack.org/manila/latest/",
            "magnum": "https://docs.openstack.org/magnum/latest/",
            "telemetry": "https://docs.openstack.org/ceilometer/latest/",
        },
        "assign": openstack,
    },
    {
        "platformKey": "ProxmoxVE",
        "platformName": "Proxmox Virtual Environment",
        "evaluationBasisType": "ProductVersion",
        "evaluatedBaseline": "Proxmox VE 8.x public documentation baseline (2026-09) plus Proxmox Backup Server",
        "evidenceSource": "Proxmox VE and PBS official wiki/documentation",
        "supportingComponents": ["KVM", "pve-cluster", "Ceph optional", "Proxmox Backup Server"],
        "solutionComponents": [
            {"Component": "Proxmox VE", "Role": "KVM virtualization and cluster"},
            {"Component": "KVM/QEMU", "Role": "Hypervisor"},
            {"Component": "Ceph", "Role": "Optional SDS"},
            {"Component": "Proxmox Backup Server", "Role": "Backup/restore"},
        ],
        "disclaimer": "SME mapping of public Proxmox VE/PBS documentation to CN v0.3 FeatureIDs. Evidence-Backed Draft only. Confirm PVE/PBS point releases before advisory sign-off.",
        "evidenceCatalog": {
            "pve": "https://pve.proxmox.com/pve-docs/",
            "ceph": "https://pve.proxmox.com/wiki/Deploy_Hyper-Converged_Ceph_Cluster",
            "sdn": "https://pve.proxmox.com/pve-docs/chapter-pvesdn.html",
            "pbs": "https://pbs.proxmox.com/docs/",
            "api": "https://pve.proxmox.com/wiki/Proxmox_VE_API",
        },
        "assign": proxmox,
    },
]


def main():
    for spec in PLATFORMS:
        assign = spec.pop("assign")
        features = all_features(assign)
        obj = {**spec, "status": "evidence_backed_draft", "features": features}
        path = OUT / f"{spec['platformKey']}_Evidence_Map_v1.json"
        path.write_text(json.dumps(obj, indent=2) + "\n")
        counts = {}
        for v in features.values():
            counts[v["parity"]] = counts.get(v["parity"], 0) + 1
        print(spec["platformKey"], counts, "wrote", path.name)


if __name__ == "__main__":
    main()
